spring.application.name=gestao-financeira-api-Hexagonal-J25

spring.datasource.url=${DB_URL2}
spring.datasource.username=${DB_USER1}
spring.datasource.password=${DB_PASSWORD1}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=disable

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
